### ISSUE TITLE
Cannot Install loverocks on Windows

### ISSUE THREAD

**Issue by Admicos** [Alloyed/loverocks#6]
I cannot install loverocks.

I have Visual Studio 2015 (which is probably the problem) in Windows 8.1 and i'm using the VS2015 Developer Command Prompt (as Administrator) to install loverocks.
I installed lua and luarocks using [Lua for Windows](https://github.com/rjpcomputing/luaforwindows) (if that helps)

The error i get is:
```
Microsoft (R) Incremental Linker Version 14.00.23918.0
Copyright (C) Microsoft Corporation.  All rights reserved.

rclauncher.obj : error LNK2019: unresolved external symbol _printf referenced in function _report
rclauncher.obj : error LNK2019: unresolved external symbol ___iob_func referenced in function _report
bin\loverocks.exe : fatal error LNK1120: 2 unresolved externals

Error: Build error: Build error in wrapper binaries
```

Is there something i missed?

**Comment by Alloyed** [comment]
Just looking at the LFW readme, it looks like it ships with luarocks 2.0.2, which is old enough that I never bothered to test with it

This may or may not be the problem, I dunno when it comes to Windows, but I can say that I got loverocks working using Windows 8.1, VS2015, and the official luarocks installer from here:
<http://keplerproject.github.io/luarocks/releases/>

Beyond that I also had to manually add the `luarocks/bin` directory(where luarocks.exe is) _and_ something along the lines of `luarocks/systree/bin` (where loverocks.bat should be) to my $PATH so I could just type loverocks into a command prompt and have it work.

I'll see if I can't reproduce this myself with LFW, and having more detailed windows install instructions couldn't hurt either

**Comment by Admicos** [comment]
I tried using the uplated luarocks, but luafilesystem wouldn't install for
some reason. Now i got that installed i'm gonna try updating luarocks to
see if that works.

**Comment by Admicos** [comment]
I tried with a updated luarocks, now installed without any errors.
